site_name: Dante's Crest Wiki
site_url: https://lust-interactive.github.io/DantesCrestWiki/
repo_url: https://github.com/lust-interactive/dantescrestwiki/
repo_name: lust-interactive/dantescrestwiki
site_description: Dante's Crest Wiki
site_author: Lust Interactive Ltd
copyright: Copyright(c) Lust Interactive Ltd, 2023
docs_dir: data
site_dir: _site/

nav:
    - Wiki Home: index.md
    - Game Roadmap: gameroadmap.md
    - Classes:
      - Shade: shade.md
      - Chaotic Good:
        - Archer: archer.md
        - Druid: druid.md
        - Monk: monk.md
        - Paladin: paladin.md
        - Priest: priest.md
      - Chaotic Neutral:
        - Alchemist: alchemist.md
        - Bard: bard.md
        - Engineer: engineer.md
        - Rogue: rogue.md
        - Witch Doctor: witchdoctor.md
      - Chaotic Evil:
        - Dread Knight: dreadknight.md
        - Necromancer: necromancer.md
        - Shadowblade: shadowblade.md
        - Sorcerer: sorcerer.md
        - Warlock: warlock.md
    - Mechanics:
      - Alliances: alliances.md
      - Attributes: attributes.md
      - Battlegrounds: battlegrounds.md
      - Combat: combat.md
      - Crafting: crafting.md
      - Currency: currency.md
      - Dungeons: dungeons.md
      - Enchanting: enchanting.md
      - Equipment: equipment.md
      - Factions: factions.md
      - Instanced Dungeons: instanceddungeons.md
      - Items: items.md
      - Leveling: leveling.md
      - Mounts: mounts.md
      - Portals: portals.md
      - Quests: quests.md
    - Professions:
      - Alchemist: alchemist.md
      - Blacksmith: blacksmith.md
      - Carpenter: carpenter.md
      - Cook: cook.md
      - Enchanter: enchanter.md
      - Engineer: engineer.md
      - Jeweler: jeweler.md
      - Leatherworker: leatherworker.md
      - Tailor: tailor.md
      - Tinkerer: tinkerer.md
    - Lust Universe:
      - Lore: lore.md
      - Recuring Characters: recuringcharacters.md
    - Links:
      - Discord: https://discord.gg/XN6YRfSMMt
theme:
  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.ico
  logo: img/dantes_crest_logo_base.png
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: d9c349
      accent: d9c349
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: d9c349
      accent: d9c349
extra:
  social:
    - icon: fontawesome/brands/wikipedia-w
      link: https://lust-interactive.github.io/DantesCrestWiki/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/XN6YRfSMMt

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/smoothScrolling.js
